before_script:
  - pwd
  - node -v

stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  cache:
    key: node_modules
    paths:
      - node_modules/
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn lint

build:
  stage: build
  cache:
    key: node_modules
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn build
  artifacts:
    paths:
      - bld
    expire_in: 1 hour

deploy:
  stage: deploy
  only:
    - master
  cache:
    key: node_modules
    paths:
      - node_modules/
    policy: pull
  script:
    - ./scripts/gitlab-ci-deploy.sh
