version: "3"
services:
  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo_data_internal:/data/db/
    networks:
      - webnet

  zookeeper:
    image: zookeeper:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  makeflow_issue_synchronizer:
    build: .
    depends_on:
      - mongo
      - zookeeper
    ports:
      - "8888:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongo_data_internal:
    external: true
